package com.dev.spring.pradeepit.mapper;

import com.dev.spring.pradeepit.dto.EmployeeDTO;
import com.dev.spring.pradeepit.entity.EmployeeEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper(unmappedTargetPolicy = org.mapstruct.ReportingPolicy.IGNORE)
public interface EmployeeMapper {
    EmployeeMapper INSTANCE = Mappers.getMapper(EmployeeMapper.class);

    //@Mapping(target = "eid", ignore = true) // Ignore mapping of eid, as it's generated by the database
    EmployeeEntity dtoToEntity(EmployeeDTO dto);

    EmployeeDTO entityToDto(EmployeeEntity entity);
}

